student:
  stu-id: 1
  stu-name: tom
  graduated: false
  subject:
    - java
    - php
    - golang
  birthday: 2002/12/10
  teachers:
    java: ary
    php: jerry
    golang: wang
  address:
    province: 广东
    city: 广州
    street: 中环西路
